# Generated by Django 2.2.14 on 2020-07-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('enerygy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ASH', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Carbohydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('potasium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
