# Generated by Django 2.2.14 on 2020-09-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0002_auto_20200717_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Arabic_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='foodtable',
            name='the_ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodtable',
            name='item_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.FoodGroup'),
        ),
    ]
