# Generated by Django 2.2.14 on 2020-09-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0003_auto_20200905_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtable',
            name='refuse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='foodtable',
            name='water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
