# Generated by Django 2.2.14 on 2020-09-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0006_choises'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('english_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('home_standrd', models.CharField(blank=True, max_length=200, null=True)),
                ('home_standrd_wieght', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=1000, null=True)),
                ('standard_unit_count', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.Choises')),
                ('item_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.ItemGroup')),
            ],
        ),
    ]
