# Generated by Django 2.2.14 on 2020-09-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0007_itemgroup_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='standard_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.Choises'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.FoodTable'),
        ),
    ]
