# Generated by Django 2.2.14 on 2020-09-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0009_auto_20200929_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='item_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.ItemGroup'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='standard_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.Choises'),
        ),
    ]
