# Generated by Django 2.2.14 on 2020-09-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0010_auto_20200929_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='standard_unit_count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True),
        ),
    ]
