# Generated by Django 2.2.14 on 2020-09-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0011_auto_20200929_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='avaliable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
