# Generated by Django 2.2.14 on 2020-10-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodconf', '0012_unit_avaliable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='meals',
            field=models.ManyToManyField(to='foodconf.Meals'),
        ),
    ]
