# Generated by Django 2.2.14 on 2020-09-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodconf', '0011_auto_20200929_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wieght', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.FoodTable')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.Unit')),
            ],
        ),
    ]
