# Generated by Django 2.2.14 on 2020-09-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_foodmix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msureunit',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.FoodTable'),
        ),
        migrations.AlterField(
            model_name='msureunit',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodconf.Unit'),
        ),
    ]
