# Generated by Django 2.2.14 on 2020-09-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20200929_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='msureunit',
            name='count',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
    ]
