# Generated by Django 2.2.14 on 2020-10-02 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20201002_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='adress_one',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='adress_tow',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='strat_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 2, 19, 59, 16, 938678)),
        ),
    ]
